// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadMonitor = { id: string, description: string,
/**
 * Summary interval in minutes; null identifies monitor_realtime.
 */
intervalMinutes: number | null, };
