//! Startup phrases retained from the approved greeting list (PR #10248).
//! One selection is shared by the provisional, live, and committed session headers.

use rand::Rng;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) struct Greeting {
    pub(crate) phrase: &'static str,
}

impl Greeting {
    pub(super) fn choose() -> Self {
        Self {
            phrase: GREETINGS[rand::rng().random_range(0..GREETINGS.len())],
        }
    }
}

const GREETINGS: &[&str] = &[
    "Whoa, fancy meeting you here!",
    "Look who’s at the keyboard.",
    "Hello, you. Got an idea?",
    "Nice to see you in these parts.",
    "Pull up a prompt.",
    "What brings you to this corner of the terminal?",
    "Hey there. Big plans or little fixes?",
    "What are we getting into today?",
    "Got something you want to try?",
    "What’s today’s little adventure?",
    "Anything interesting on the docket?",
    "Take your time. The cursor can wait.",
    "A half-formed idea will do.",
    "Come on in. There’s room for an idea.",
    "You, me, and a blinking cursor.",
    "It takes two to tango. What’s our first step?",
    "You bring the idea. I’ll bring the brackets.",
    "Your move, teammate.",
    "What are we cooking up?",
    "Shall we turn “what if” into something?",
    "What’s the first thing on our napkin sketch?",
    "Bring your unfinished thoughts.",
    "You set the direction. We’ll work out the steps.",
    "Ah, the terminal. A classic meeting spot.",
    "Nice place you’ve got here. Very monospace.",
    "Welcome to our little rectangle of possibility.",
    "A cursor blinks. The plot thickens.",
    "The prompt is yours.",
    "Fancy a little quality terminal time?",
    "How’s life between the brackets?",
    "Shall we give this cursor a purpose?",
    "A fresh prompt. An open question.",
    "Your keyboard has entered the chat.",
    "Hello, world. Hello, you.",
    "Welcome to the blinking edge of possibility.",
    "Any loose ends? Semicolons count.",
    "Shall we make this terminal earn its keep?",
    "Got an itch to fix a thing?",
    "Show me the bit that’s being weird.",
    "Greetings, fellow tinkerer.",
    "Well, well, well. An idea approaches.",
    "What’s today’s side quest?",
    "Is this a plan day or a poke-around day?",
    "Practical, peculiar, or a little of both?",
    "Rough sketches welcome.",
    "Shall we see where this goes?",
    "All right. What have you got?",
    "Back for another round?",
    "Same terminal, new possibilities.",
    "Welcome back. Familiar territory or a fresh adventure?",
    "Follow the white cursor.",
    "Welcome to the command line, Neo.",
    "A glitch in the Matrix, or just a missing semicolon?",
    "How deep does this codebase go?",
    "Speak, friend, and enter a prompt.",
    "One prompt to begin the journey.",
    "May the source be with you.",
    "These might be the bugs you’re looking for.",
    "A new prompt awakens.",
    "Forty-two is an answer. What’s the question?",
    "It’s dangerous to code alone. Take a prompt.",
    "The code must flow.",
    "You rang? Metaphorically. You typed.",
    "Hello again, carbon-based collaborator.",
    "This looks like the start of a perfectly reasonable rabbit hole.",
    "Shall we turn “huh?” into “aha!”?",
    "Well, this terminal just got interesting.",
    "The source is strong with this one.",
    "There’s a perfectly good prompt with your name on it.",
    "Here for a quick fix or the extended edition?",
    "What’s the latest from your side of the keyboard?",
    "Got a minute and a mildly unreasonable idea?",
    "A hunch is a perfectly respectable starting point.",
    "Hello again. What’s the plot this time?",
    "Shall we make a little something out of nothing?",
    "Welcome to the neighborhood. Lots of characters here.",
    "Nice terminal. Does it come in widescreen?",
    "Your cursor called. It wants a plot.",
    "Shall we put some verbs after that cursor?",
    "Welcome. There’s no dress code, just code.",
    "This terminal has excellent conversational potential.",
    "Got an idea that won’t stay on the napkin?",
    "What are we building in this episode?",
    "Bring a question. Bonus points if it’s a weird one.",
    "What are we poking with a metaphorical stick?",
    "Shall we make the thing that makes the other thing easier?",
    "Welcome to the part where the idea gets interesting.",
    "A long time ago, in a directory not so far away…",
];
